emprego/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'emprego'

urlpatterns = [
    path('', views.emprego, name='emprego'),
    path('<categoria_slug>/', views.emprego, name='list_by_categoria'),
    path('ajax/<title>/<id>/', views.ajax_detail, name='ajax_detail'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Inicio, name='inicio'),
    path('restaurante/', views.RestauranteView.as_view(), name='restaurante'),
    path('servicos/', views.ServicoView.as_view(), name='servico'),
    path('noticia/', views.NoticiaView.as_view(), name='noticia'),
    path('historia/', views.SobreView.as_view(), name='sobre_dundo'),
    path('patrimonio/', views.PatrimonioView.as_view(), name='patrimonio'),
    path('contacto/', views.contacto, name='contacto'),
]

portaldundo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('hospedagem/', include('hospedagem.urls')),
    path('emprego/', include('emprego.urls')),
    path('evento/', include('evento.urls')),
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

emprego/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.urls import reverse

from django.db.models import Q

class EmpregoManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) |
                         Q(text__icontains=query) |
                         Q(empresa__icontains=query)
                         )
            qs = qs.filter(or_lookup).distinct()  # distinct() is often necessary with Q lookups
        return qs

class Categoria(models.Model):
    nome = models.CharField('Nome', max_length=200, db_index=True)
    slug = models.SlugField('Slug', max_length=200, db_index=True, unique=True)

    icons = (
        ('<i class="fas fa-laptop"></i>', 'Informática e Telecomunicações'),
        ('<i class="fas fa-futbol"></i>', 'Desporto e Fitness'),
        ('<i class="fas fa-medkit"></i>', 'Saúde e Beleza'),
        ('<i class="fas fa-wrench"></i>', 'Reparação e Manutenção'),
        ('<i class="fas fa-shopping-basket"></i>', 'Assistente de Loja e Caixa'),
        ('<i class="fas fa-leaf"></i>', 'Agricultura e Jardinagem'),
        ('<i class="far fa-chart-bar"></i>', 'Finanças e Contabilidade'),
        ('<i class="fas fa-lock"></i>', 'Segurança e Vigilância'),
        ('<i class="fas fa-user-graduate"></i>', 'Formação e Educação'),
        ('<i class="fas fa-hotel"></i>', 'Restauração, Hotelaria e Turismo'),
        ('<i class="fas fa-people-carry"></i>', 'Construção'),
        ('<i class="fas fa-store"></i>', 'Comercial'),
        ('<i class="far fa-calendar-alt"></i>', 'Publicidade e Eventos'),
        ('<i class="fas fa-broom"></i>', 'Domésticos e Limpezas'),
        ('<i class="fas fa-car"></i>', 'Transportes e Logística'),
        ('Outros', 'Outros'),
    )
    icon = models.CharField(
        max_length=40,
        choices=icons,
        default='Outros',
    )

    class Meta:
        ordering = ('nome',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nome

    def get_absolute_url(self):
        return reverse('emprego:list_by_categoria', args=[self.slug])

class Endereco(models.Model):
    rua = models.CharField('Rua', max_length=200)
    city = models.CharField('Cidade',max_length=200)
    province = models.CharField('Provincia',max_length=100)
    code = models.CharField('Codigo Postal',max_length=5)

    def __str__(self):
        return self.city

class Emprego(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    title = models.CharField('Titulo', max_length=250)
    text = models.TextField('Detalhes')
    empresa = models.CharField('Nome da Entidade', max_length=100)
    image = models.ImageField('Imagem', upload_to="media/images", blank=True)
    endereco = models.ForeignKey(Endereco, on_delete=models.CASCADE, related_name="Endereco")
    pub_data = models.DateTimeField('Publicado')
    disponivel = models.BooleanField(default=True)

    objects = EmpregoManager()

    class Meta:
        ordering = ('pub_data',)
        verbose_name = 'emprego'
        verbose_name_plural = 'empregos'

    def __str__(self):
        return self.title

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_data <= now

emprego/views.py
import json
from django.http import Http404, HttpResponse

from django.shortcuts import render, get_object_or_404
from .models import Emprego, Categoria
from django.utils import timezone
from django.contrib.humanize.templatetags.humanize import naturalday

def emprego(request, categoria_slug=None):
    categoria = None
    categorias = Categoria.objects.all()
    empregos = Emprego.objects.filter(disponivel=True, pub_data__lte=timezone.now()).order_by('-pub_data')[:5]
    template_name = "emprego.html"
    if categoria_slug:
        categoria = get_object_or_404(Categoria, slug=categoria_slug)
        empregos = Emprego.objects.filter(categoria=categoria)

    return render(request, template_name, {'empregos': empregos,
                                           'categorias': categorias,
                                           'categoria':categoria,})

def ajax_detail(request, title, id):
    emprego = get_object_or_404(Emprego, id=id, title=title)

    if request.is_ajax():
        data = {
            'title': emprego.title,
            'empresa': emprego.empresa,
            'text':emprego.text,
            'imagem_url':json.dumps(str(emprego.image)),
            'endereco':json.dumps(str(emprego.endereco)),
            'date':naturalday(emprego.pub_data),
        }
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        raise Http404

emprego/templates/emprego.html
{% extends 'base.html' %}

{% block title %}Empregos{% endblock %}

{% load static %}
{% load humanize %}

{% block style %} <link href="{% static 'css/emprego.css' %}"  rel="stylesheet">{% endblock %}

{% block content %}
<section>
    <div class="container emprego">

        <div class="dropdown show d-flex justify-content-center pb-3">
          <a class="btn btn-primary dropdown-toggle" href="{% url 'emprego:emprego' %}" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {% if not categoria %}Todas{% else %}{{categoria.icon |safe }} {{ categoria.nome }}{% endif %}
          </a>

          <div class="dropdown-menu rounded-0" aria-labelledby="dropdownMenuLink">
              {% if categoria %}
              <a class="dropdown-item" href="{% url 'emprego:emprego' %}">Todas</a>
              {% endif %}

              {% for c in categorias %}
                  {% if categoria.slug == c.slug %}
                    <a class="dropdown-item selected" href="{{ c.get_absolute_url }}">{{c.icon |safe }} {{ c.nome }}<i class="fa fa-check" aria-hidden="true"></i></a>
                  {% else%}
                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{c.icon |safe }} {{ c.nome }}</a>
                  {% endif %}
              {% endfor %}
          </div>
        </div>

        {% for emprego in empregos %}
                <div class="d-flex border border-secondary p-1 emprego" style="max-height:180px"><!-- -->
                    <div class="mr-5" style="max-width:100px">
                        <img style="height:100px" class="rounded-circle" src="{% if emprego.image %}{{ emprego.image.url }}{% else %}{% static "images/Not_available.jpg" %}{% endif %}">
                    </div>
                    <div class="d-flex flex-column ml-5">
                        <a href="" class="card-links"  id="title" onclick="getEmpregoDetail('{{emprego.id}}', '{{emprego.title}}', '{% url 'emprego:ajax_detail' id=emprego.id title=emprego.title %}')" data-toggle="modal" data-target=".empregoModal">{{emprego.title}}</a>
                        <p class="">{{emprego.empresa}}</p>
                        <div class="d-inline-flex">
                            <small class="text-sm-left"><i class="fas fa-map-marker-alt"></i> <b>{{emprego.endereco}}</b> {{emprego.pub_data|naturalday}}</small>
                        </div>
                    </div>
                </div>


        <br>
        {% empty %}
            <div class="d-flex justify-content-center text-center pt-5 pb-5 mt-5 mb-5">
                    <div class="card border-secondary col-lg-6 pt-4 pb-4">
                      <div class="card-body text-secondary">
                        <h3 class="card-title">Sem empregos disponiveis</h3>
                        <h1><i class="far fa-frown"></i></h1>
                      </div>
                    </div>
            </div>
        {% endfor %}


        <!-- Modal -->


    </div>

</section>
{% endblock %}

{% block js %}


    function getEmpregoDetail(id, title, url){
        var modal = "<div class='modal fade empregoModal' tabindex='-1' role='dialog' aria-labelledby='empregoModal' aria-hidden='true'></div>";
        $(".emprego").prepend(modal);

        $.ajax({
            type: "GET",
            url: url,
            dataType: 'json',
            success: function(data) {
                if (data) {
                    criarModal(data);
                }
            }
        });
    }

    function criarModal(emprego){
        var modal_dialog = "<div class='modal-dialog modal-lg'></div>";
        var modal_content = " <div class='modal-content rounded-0'></div>";
        var modal_header = "<div class='modal-header'></div>";
        var modal_title = "<h5 class='modal-title'></h5>";
        var closeModalBtn = "<button type='button' class='close' aria-label='Close' onclick='closeModal()'><span aria-hidden='true'>&times;</span></button>";
        var modal_body = "<div class='modal-body'><div class='row'><div class='col-md-3'><img class='rounded-circle emprego-img' src=''><small class='emprego-empresa'></small><br><small class='text-muted emprego-endereco'></small><br><small class='text-muted emprego-pub-data'></small></i></div><div class='col-md-9'><p class='emprego-text'></p></div></div></div>";
        var modal_footer = "<div class='modal-footer'><button type='button' class='btn btn-primary'>Enviar mensagem</button><button type='button' class='btn btn-secondary'>Ligar</button></div>";
        var location_icon = "<i class='fas fa-map-marker-alt'></i>";
        var clock_icon = "<i class='far fa-clock'></i>";

        $(".modal").append(modal_dialog);
        $(".modal-dialog").append(modal_content);
        $(".modal-content").append(modal_header);
        $(".modal-header").append(modal_title);
        $(".modal-header").append(closeModalBtn);
        $(".modal-content").append(modal_body);
        $(".modal-content").append(modal_footer);


        $(".modal-title").html(emprego.title);
        $(".modal-body .emprego-empresa").html(emprego.empresa);
        $(".modal-body .emprego-text").html(emprego.text);

        var url = emprego.imagem_url.replace(/^"(.*)"$/, '$1');
        if(!!url){
            $(".emprego-img").attr("src", "http://localhost:8089/media/"+url);
        }else{
            $(".emprego-img").attr("src", "http://localhost:8089/static/images/Not_available.jpg");
        }
        $(".modal-body .emprego-endereco").html(location_icon + " <b>"+emprego.endereco.replace(/^"(.*)"$/, '$1')+"</b>");
        $(".modal-body .emprego-pub-data").html(clock_icon + " " + emprego.date);

    }

    function closeModal(){
        $('.modal-backdrop').fadeOut(function(){ $(this).remove();});
        $('.modal').addClass('animated fadeOutUp', function(){ $(this).remove();});
    }
{% endblock %}